ci(func tests): try to fix

diff --git a/start-ci b/start-ci
--- a/start-ci
+++ b/start-ci
@@ -1,7 +1,29 @@
 #!/usr/bin/env bash
 
-chmod a+x bin/startServer
+chmod a+x bin/startServerInTestingMode
 
-chmod a+x docker-compose/scripts/*
+docker-compose -f docker-compose/ci.yml up -d
 
-exec docker-compose -f docker-compose/ci.yml up
+echo "[$(date)] - Starting..."
+
+npm run test:func
+FUNC_TESTS_EXIT_CODE=$? # store the tests exit code
+
+if [ $FUNC_TESTS_EXIT_CODE -eq 0 ]
+then
+  echo ''
+  echo ''
+  echo -e "\e[32mFunctional tests passed !\e[0m"
+  echo ''
+  echo ''
+else
+  echo ''
+  echo ''
+  echo -e "\e[31Functional tests failed...\e[0m"
+  echo ''
+  echo ''
+fi
+
+docker-compose -f docker-compose/ci.yml kill
+exit $FUNC_TESTS_EXIT_CODE
+
